version: "3.9"

services:
  web:
    build: .
    container_name: restaurant_web
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: ["gunicorn", "wsgi:app", "-b", "0.0.0.0:8000", "-w", "2"]

  db:
    image: postgres:16-alpine
    container_name: restaurant_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
